framework:
    router:
<<<<<<< HEAD
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(DEFAULT_URI)%'
=======
        utf8: true

        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost
>>>>>>> bc36c7eda1c65bfa3ceead6ff712c986f06cb49c

when@prod:
    framework:
        router:
            strict_requirements: null
