when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
<<<<<<< HEAD
        profiler:
            collect: false
            collect_serializer_data: true
=======
        profiler: { collect: false }
>>>>>>> bc36c7eda1c65bfa3ceead6ff712c986f06cb49c
