when@dev:
    web_profiler_wdt:
<<<<<<< HEAD
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.php'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.php'
=======
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
>>>>>>> bc36c7eda1c65bfa3ceead6ff712c986f06cb49c
        prefix: /_profiler
